project_id = "vshnlthiliesnbyqswrs"

[functions.google-drive-proxy]
verify_jwt = false

[functions.ai-document-analyzer]
verify_jwt = false

[functions.document-embedder]
verify_jwt = false

[functions.vector-search]
verify_jwt = false

[functions.diagram-generator]
verify_jwt = false

[functions.mcp-server]
verify_jwt = false

[functions.advanced-rag-processor]
verify_jwt = false

[functions.ocr-processor]
verify_jwt = false

[functions.google-apps-script-proxy]
verify_jwt = false

[functions.advanced-rag-processor]
verify_jwt = false
