// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get environment variables from .env file
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://vshnlthiliesnbyqswrs.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzaG5sdGhpbGllc25ieXFzd3JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNjM3MzAsImV4cCI6MjA3MTgzOTczMH0.KahPIxexRJEOq_EiVhTJa1Q36AdtqoDtRV_6Tg6sU3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Add a function to check connection status
export const checkSupabaseConnection = async () => {
  try {
    const { data, error } = await supabase.from('documents').select('id').limit(1);
    if (error) throw error;
    return true;
  } catch (error) {
    console.error('Supabase connection error:', error);
    return false;
  }
};